image: alpine:3.9.4
pipelines:
  custom:
    terraform-apply:
      - step:
          script:
            - apk --no-cache add curl jq
            - export CONFIG_VARS_JSON=$(curl -sSf
              -H "Authorization:Bearer $HEROKU_API_KEY"
              -H "Accept:application/vnd.heroku+json; version=3"
              https://api.heroku.com/apps/bus-api-terraform-backend/config-vars)
            - export DATABASE_URL=$(echo $CONFIG_VARS_JSON | jq -r '.DATABASE_URL')
            - export BUS_API_CLIENT_COMMIT=$(echo $CONFIG_VARS_JSON | jq -r '.BUS_API_CLIENT_COMMIT')
            - export BUS_API_SERVER_COMMIT=$(echo $CONFIG_VARS_JSON | jq -r '.BUS_API_SERVER_COMMIT')
            - curl -sSfLo bus_api_client-$BUS_API_CLIENT_COMMIT.tar.gz
              https://bitbucket.org/robertograham/bus-api-client/get/$BUS_API_CLIENT_COMMIT.tar.gz
            - curl -sSfLo bus_api_server-$BUS_API_SERVER_COMMIT.tar.gz
              -u $BITBUCKET_REPO_OWNER:$BITBUCKET_PASSWORD
              https://bitbucket.org/robertograham/bus-api/get/$BUS_API_SERVER_COMMIT.tar.gz
            - echo 1 | docker run
              -i
              -v $(pwd):/data
              -w /data
              -e HEROKU_API_KEY=$HEROKU_API_KEY
              -e HEROKU_EMAIL=$HEROKU_EMAIL
              hashicorp/terraform:light init -backend-config="conn_str=$DATABASE_URL"
            - docker run
              -v $(pwd):/data
              -w /data
              -e TF_VAR_transport_api_app_id=$TRANSPORT_API_APP_ID
              -e TF_VAR_transport_api_app_key=$TRANSPORT_API_APP_KEY
              -e TF_VAR_client_commit=$BUS_API_CLIENT_COMMIT
              -e TF_VAR_server_commit=$BUS_API_SERVER_COMMIT
              -e HEROKU_API_KEY=$HEROKU_API_KEY
              -e HEROKU_EMAIL=$HEROKU_EMAIL
              hashicorp/terraform:light plan
              -var client_app_name=prod-bus-api-client
              -var server_app_name=prod-bus-api-server
              -out=current.tfplan
            - docker run
              -v $(pwd):/data
              -w /data
              -e HEROKU_API_KEY=$HEROKU_API_KEY
              -e HEROKU_EMAIL=$HEROKU_EMAIL
              hashicorp/terraform:light apply current.tfplan
          services:
            - docker
          caches:
            - docker