image: atlassian/default-image:2

pipelines:
  custom:
    release:
      - variables:
          - name: BUS_API_CLIENT_BUILD_NUMBER
          - name: BUS_API_SERVER_BUILD_NUMBER
      - step:
          services:
            - docker
          caches:
            - docker
          script:
            - curl --silent 
              --show-error 
              --fail 
              --location 
              --output bus_api_client-$BUS_API_CLIENT_BUILD_NUMBER.tar.gz
              https://bitbucket.org/robertograham/bus-api-client/get/$BUS_API_CLIENT_BUILD_NUMBER.tar.gz
            - curl --silent 
              --show-error 
              --fail 
              --location 
              --output bus_api_server-$BUS_API_SERVER_BUILD_NUMBER.tar.gz
              https://bitbucket.org/robertograham/bus-api/get/$BUS_API_SERVER_BUILD_NUMBER.tar.gz
            - export DATABASE_URL=$(curl --silent --show-error --fail https://api.heroku.com/apps/bus-api-terraform-backend/config-vars
              -H "Authorization:Bearer $HEROKU_API_KEY"
              -H "Accept:application/vnd.heroku+json; version=3"
              | jq -r '.DATABASE_URL')  
            - echo 1 
              | docker run 
              -i 
              -v $(pwd):/data 
              -w /data
              -e HEROKU_API_KEY=$HEROKU_TOKEN
              -e HEROKU_EMAIL=$HEROKU_EMAIL
              hashicorp/terraform:light init -backend-config="conn_str=$DATABASE_URL"
            - docker run 
              -v $(pwd):/data
              -w /data
              -e TF_VAR_transport_api_app_id=$TRANSPORT_API_APP_ID
              -e TF_VAR_transport_api_app_key=$TRANSPORT_API_APP_KEY
              -e TF_VAR_client_build_number=$BUS_API_CLIENT_BUILD_NUMBER 
              -e TF_VAR_server_build_number=$BUS_API_SERVER_BUILD_NUMBER
              -e HEROKU_API_KEY=$HEROKU_TOKEN
              -e HEROKU_EMAIL=$HEROKU_EMAIL
              hashicorp/terraform:light plan 
              -var client_app_name=prod-bus-api-client 
              -var server_app_name=prod-bus-api-server
              -out=current.tfplan