image: atlassian/default-image:2

pipelines:
  custom:
    release:
      - variables:
          - name: BUS_API_CLIENT_BUILD_NUMBER
          - name: BUS_API_SERVER_BUILD_NUMBER
      - step:
          services:
            - docker
          caches:
            - docker
          script:
            - export DATABASE_URL=$(curl --silent --show-error --fail https://api.heroku.com/apps/bus-api-terraform-backend/config-vars
              -H "Authorization:Bearer $HEROKU_API_KEY"
              -H "Accept:application/vnd.heroku+json; version=3"
              | jq -r '.DATABASE_URL')
            - wget https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_linux_amd64.zip  
            - unzip terraform_0.12.3_linux_amd64.zip
            - mv terraform /usr/local/bin/
            - echo 1 | terraform init -backend-config="conn_str=$DATABASE_URL"