version: 2.0
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.12.10
    steps:
      - checkout
      - run:
          command: |
            apk add --no-cache curl jq
            for keyEqualsValueString in $(curl -sSf \
            -H "Authorization:Bearer $HEROKU_API_KEY" \
            -H "Accept:application/vnd.heroku+json; version=3" \
            https://api.heroku.com/apps/departure-infra-backend/config-vars \
            | jq -r "to_entries|map(\"TF_VAR_\(.key|ascii_downcase)=\(.value|tostring)\")|.[]"); \
            do export $keyEqualsValueString; done
            terraform init -input=false -backend-config="conn_str=$TF_VAR_database_url"
            terraform plan -out=tfplan -input=false
            terraform apply -input=false tfplan
workflows:
  version: 2
  approval-and-build:
    jobs:
      - build:
          filters:
            branches:
              only: master
