version: 2.0
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends curl jq
            for keyEqualsValueString in $(curl -sSf \
            -H "Authorization:Bearer $HEROKU_API_KEY" \
            -H "Accept:application/vnd.heroku+json; version=3" \
            https://api.heroku.com/apps/bus-api-terraform-backend/config-vars \
            | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]"); \
            do export $keyEqualsValueString; done
            curl -sSfLo bus_api_client-$BUS_API_CLIENT_COMMIT.tar.gz \
            https://github.com/RobertoGraham/departure-app/archive/$BUS_API_CLIENT_COMMIT.tar.gz
            curl -sSfLo bus_api_server-$BUS_API_SERVER_COMMIT.tar.gz \
            https://github.com/RobertoGraham/departure-api/archive/$BUS_API_SERVER_COMMIT.tar.gz
            pwd
            ls
            echo 1 | docker run \
            -i \
            -v $(pwd):/data \
            -w /data \
            -e HEROKU_API_KEY=$HEROKU_API_KEY \
            -e HEROKU_EMAIL=$HEROKU_EMAIL \
            hashicorp/terraform:0.12.9 init -backend-config="conn_str=$DATABASE_URL"
            docker run \
            -v $(pwd):/data \
            -w /data \
            -e HEROKU_API_KEY=$HEROKU_API_KEY \
            -e HEROKU_EMAIL=$HEROKU_EMAIL \
            hashicorp/terraform:0.12.9 plan \
            -var client_app_name=prod-bus-api-client \
            -var server_app_name=prod-bus-api-server \
            -var transport_api_app_id=$TRANSPORT_API_APP_ID \
            -var transport_api_app_key=$TRANSPORT_API_APP_KEY \
            -var client_commit=$BUS_API_CLIENT_COMMIT \
            -var server_commit=$BUS_API_SERVER_COMMIT \
            -out=current.tfplan
            docker run \
            -v $(pwd):/data \
            -w /data \
            -e HEROKU_API_KEY=$HEROKU_API_KEY \
            -e HEROKU_EMAIL=$HEROKU_EMAIL \
            hashicorp/terraform:0.12.9 apply current.tfplan
workflows:
  version: 2
  approval-and-build:
    jobs:
      - hold:
          filters:
            branches:
              only: master
          type: approval
      - build:
          requires:
            - hold
