version: 2.0
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends curl jq
            for keyEqualsValueString in $(curl -sSf \
            -H "Authorization:Bearer $HEROKU_API_KEY" \
            -H "Accept:application/vnd.heroku+json; version=3" \
            https://api.heroku.com/apps/departure-infra-backend/config-vars \
            | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]"); \
            do export $keyEqualsValueString; done
            export TERRAFORM_VERSION=0.12.10
            docker pull hashicorp/terraform:$TERRAFORM_VERSION
            docker tag hashicorp/terraform:$TERRAFORM_VERSION terraform
            echo 1 | docker run \
            -i \
            -v $(pwd):/data \
            -w /data \
            -e HEROKU_API_KEY=$HEROKU_API_KEY \
            -e HEROKU_EMAIL=$HEROKU_EMAIL \
            terraform init -backend-config="conn_str=$DATABASE_URL"
            docker run \
            -v $(pwd):/data \
            -w /data \
            -e HEROKU_API_KEY=$HEROKU_API_KEY \
            -e HEROKU_EMAIL=$HEROKU_EMAIL \
            terraform plan \
            -var departure_app_name=prod-departure-app \
            -var departure_api_name=prod-departure-api \
            -var transport_api_app_id=$TRANSPORT_API_APP_ID \
            -var transport_api_app_key=$TRANSPORT_API_APP_KEY \
            -var departure_app_commit_hash=$DEPARTURE_APP_COMMIT_HASH \
            -var departure_api_commit_hash=$DEPARTURE_API_COMMIT_HASH \
            -out=current.tfplan
            docker run \
            -v $(pwd):/data \
            -w /data \
            -e HEROKU_API_KEY=$HEROKU_API_KEY \
            -e HEROKU_EMAIL=$HEROKU_EMAIL \
            terraform apply current.tfplan
workflows:
  version: 2
  approval-and-build:
    jobs:
      - hold:
          filters:
            branches:
              only: master
          type: approval
      - build:
          requires:
            - hold
