version: 2.1
jobs:
  apply-departure-api-terraform:
    docker:
      - image: hashicorp/terraform:0.12.25
    steps:
      - checkout
      - run:
          command: |
            apk add -q --no-progress --no-cache curl jq
            for keyEqualsValueString in $(curl -sSf \
            -H "Authorization:Bearer $HEROKU_API_KEY" \
            -H "Accept:application/vnd.heroku+json; version=3" \
            https://api.heroku.com/apps/departure-infra-backend/config-vars \
            | jq -r "to_entries|map(\"TF_VAR_\(.key|ascii_downcase)=\(.value|tostring)\")|.[]"); \
            do export $keyEqualsValueString; done
            terraform init -input=false -backend-config="conn_str=$TF_VAR_database_url" departure-api
            terraform apply -input=false -auto-approve departure-api
  apply-departure-app-terraform:
    docker:
      - image: hashicorp/terraform:0.12.25
    steps:
      - checkout
      - run:
          command: |
            apk add -q --no-progress --no-cache curl jq
            for keyEqualsValueString in $(curl -sSf \
            -H "Authorization:Bearer $HEROKU_API_KEY" \
            -H "Accept:application/vnd.heroku+json; version=3" \
            https://api.heroku.com/apps/departure-infra-backend/config-vars \
            | jq -r "to_entries|map(\"TF_VAR_\(.key|ascii_downcase)=\(.value|tostring)\")|.[]"); \
            do export $keyEqualsValueString; done
            terraform init -input=false -backend-config="conn_str=$TF_VAR_database_url" departure-app
            terraform apply -input=false -auto-approve departure-app
workflows:
  apply-departure-api-terraform:
    jobs:
      - apply-departure-api-terraform:
          filters:
            branches:
              only: master
  apply-departure-app-terraform:
    jobs:
      - apply-departure-app-terraform:
          filters:
            branches:
              only: master
