version: 2.1

parameters:
  application:
    type: string
    default: ""
  commit-hash:
    type: string
    default: ""

jobs:
  apply-terraform:
    docker:
      - image: hashicorp/terraform:0.14.4
    parameters:
      application:
        type: enum
        enum: [ "departure-api", "departure-app" ]
      commit-hash:
        type: string
    steps:
      - checkout
      - run:
          command: |
            apk add -q --no-progress --no-cache curl jq
            for keyEqualsValueString in $(curl -sSf \
            -H "Authorization:Bearer $HEROKU_API_KEY" \
            -H "Accept:application/vnd.heroku+json; version=3" \
            https://api.heroku.com/apps/departure-infra-backend/config-vars \
            | jq -r "to_entries|map(\"TF_VAR_\(.key|ascii_downcase)=\(.value|tostring)\")|.[]"); \
            do export $keyEqualsValueString; done
            cd applications/<< parameters.application >>
            terraform init -input=false -backend-config="conn_str=$TF_VAR_database_url"
            terraform apply -input=false -auto-approve -var="commit_hash=<< parameters.commit-hash >>"

workflows:
  apply-departure-api-terraform:
    when:
      and:
        - equal: [ departure-api, << pipeline.parameters.application >> ]
        - << pipeline.parameters.commit-hash >>
    jobs:
      - apply-terraform:
          commit-hash: << pipeline.parameters.commit-hash >>
          application: departure-api
          filters:
            branches:
              only: master
  apply-departure-app-terraform:
    when:
      and:
        - equal: [ departure-app, << pipeline.parameters.application >> ]
        - << pipeline.parameters.commit-hash >>
    jobs:
      - apply-terraform:
          commit-hash: << pipeline.parameters.commit-hash >>
          application: departure-app
          filters:
            branches:
              only: master